version: "3.9"
services:
  aph_if_backend:
    build: ./backend
    env_file: ./backend/.env
    container_name: aph_if_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  aph_if_data_processing:
    build: ./data_processing
    env_file: ./data_processing/.env
    container_name: aph_if_data_processing
    ports:
      - "8010:8010"
    restart: unless-stopped

  aph_if_frontend:
    build: ./frontend
    env_file: ./frontend/.env
    container_name: aph_if_frontend
    ports:
      - "8501:8501"
    depends_on:
      - aph_if_backend
    restart: unless-stopped


