[tool.ruff]
line-length = 100
target-version = "py312"
extend-select = ["I"]
exclude = ["venv", ".venv", "dist"]

[tool.mypy]
python_version = "3.12"
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
strict_optional = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"
pythonpath = ["."]


